### ISSUE TITLE
Wrapper raise jsondecode error

### ISSUE THREAD

**Issue by FishyDeveloper** [Makiyu-py/danbot-hosting#1]
Hello, I encountered something when I using this library. it raises a JSONDecodeError: Expecting value: line 1 column 1 (char 0).

Here is the full log
```
Task exception was never retrieved
future: <Task finished name='Task-20' coro=<DanBotClient._autopost() done, defined at /home/container/.local/lib/python3.8/site-packages/danbot_api/client.py:69> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/danbot_api/client.py", line 72, in _autopost
    await self.post(len(self.bot.guilds),
  File "/home/container/.local/lib/python3.8/site-packages/danbot_api/client.py", line 64, in post
    status = await check_resp_status(resp)
  File "/home/container/.local/lib/python3.8/site-packages/danbot_api/client.py", line 16, in check_resp_status
    elif resp.json()['error']:
  File "/home/container/.local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The reason why it says /home file instead of C:/path is because I use a host. And I do not think it's my code as I use the same code as the example

My code:
```python
#modules (i have so many modules imported, but it's not related)
import discord
from discord.ext import commands
import random
from danbot_api import DanBotClient

bot = commands.Bot(command_prefix=["Fb!", "fb!", "FishyBot do"],
                   case_insensitive=True, intents=discord.Intents.all(),
                   owner_id=521251505269899265)
bot.help_command = None

@bot.listen()
async def on_ready():
    await bot.change_presence(activity=discord.Game("Starting.."))
    for i in os.listdir("/home/container/Extentions"):
        if i.endswith(".py"):
            bot.load_extension(f'Extentions.{i[:-3]}')
            await asyncio.sleep(0.2)

    else:
        await bot.change_presence(activity=discord.Game(name=f'Help [fb!] | in {len(bot.guilds)} Guilds'))
        DanBotClient(bot, "danbot-cg4iwo", autopost=True) #it errors here 
        print(f'{bot.user} is ready for action!')

@bot.event
async def on_dbh_post(data):
    print("Posted Bot Data to DBH. Data Posted:")
    print(data)
    
bot.run("token")
```

**Comment by FishyDeveloper** [comment]
Actually nvm, the problem resolved
