### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by SreevikramR** [Makiyu-py/danbot-hosting#2]
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    from danbot_api import DanBotClient
  File "/home/container/.local/lib/python3.8/site-packages/danbot_api/__init__.py", line 1, in <module>
    from .client import DanBotClient
  File "/home/container/.local/lib/python3.8/site-packages/danbot_api/client.py", line 1, in <module>
    import requests as rq
ModuleNotFoundError: No module named 'requests'

**Comment by Makiyu-py** [comment]
Hi! As of version 0.2, using requests **are now deprecated**, we are now using aiohttp. So update your version!

Happy Coding!
Makiyu
